// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnxxemtzsfltumxcwtwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJueHhlbXR6c2ZsdHVteGN3dHdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MzIwMTgsImV4cCI6MjA3MzMwODAxOH0.kcEKaC6KM7m30EgNQoO6U-K67-Yw6gCqEOgMu5g8rl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});